# Generated by Django 5.0.3 on 2024-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaveOtt",
            fields=[
                (
                    "have_ott_num",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "have_ott",
                "db_table_comment": "OTT information contained in content, 컨텐츠가 가지고 있는 OTT 정보",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "test",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserLinkInfo",
            fields=[
                (
                    "user_link_num",
                    models.IntegerField(
                        db_comment="유저 연동 정보의 고유한 번호", primary_key=True, serialize=False
                    ),
                ),
                ("ott_id", models.CharField(db_comment="연동할 OTT의 ID", max_length=50)),
                (
                    "ott_password",
                    models.CharField(db_comment="연동할 OTT의 비밀번호", max_length=100),
                ),
                (
                    "ott_profile",
                    models.CharField(
                        blank=True, db_comment="연동할 OTT의 프로필", max_length=45, null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_link_info",
                "db_table_comment": "Save user linkage information, 유저 연동 정보를 저장하는 테이블",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Have_ott",
        ),
        migrations.DeleteModel(
            name="User_link_info",
        ),
        migrations.AlterModelTableComment(
            name="contents",
            table_comment="Stores collected content information, 수집한 컨텐츠 정보를 저장하는 테이블",
        ),
        migrations.AlterModelTableComment(
            name="ott",
            table_comment="Linkable OTT, 연동이 가능한 OTT",
        ),
        migrations.AlterModelTableComment(
            name="post",
            table_comment="Stores post, 게시글을 저장하는 테이블",
        ),
        migrations.AlterModelTableComment(
            name="review",
            table_comment="store review information, 리뷰 정보 저장",
        ),
        migrations.AlterModelTableComment(
            name="users",
            table_comment="Stores collected users information, 수집한 유저의 정보를 저장하는 테이블",
        ),
    ]
