# Generated by Django 5.0.3 on 2024-04-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_haveott_test_userlinkinfo_delete_have_ott_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
