# Generated by Django 5.0.3 on 2024-04-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HaveOtt",
        ),
    ]
