# Generated by Django 5.0.3 on 2024-05-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_haveott"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
    ]
