# Generated by Django 5.0.3 on 2024-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_users_options"),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name="users",
        #    name="gender",
        #),
        #migrations.RemoveField(
        #    model_name="users",
        #    name="name",
        #),
        #migrations.RemoveField(
        #    model_name="users",
        #    name="phone_number",
        #),
        #migrations.AlterField(
         #   model_name="users",
         #   name="birth",
         #   field=models.DateField(blank=True, db_comment="생년월일", null=True),
        #),
        #migrations.AlterField(
        #    model_name="users",
        #    name="email",
        #    field=models.EmailField(
        #        db_comment="이메일", max_length=50, unique=True, verbose_name="email"
        #    ),
        #),
        migrations.AlterField(
            model_name="users",
            name="nickname",
            field=models.CharField(db_comment="별명", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(db_comment="비밀번호", max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.CharField(
                db_comment="아이디", max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
