# Generated by Django 5.0.3 on 2024-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_users_gender_remove_users_name_and_more"),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name="users",
        #    name="gender",
        #),
        #migrations.RemoveField(
        #    model_name="users",
        #    name="name",
        #),
        #migrations.RemoveField(
        #    model_name="users",
        #    name="phone_number",
        #),
        #migrations.AlterField(
        #    model_name="users",
        #    name="email",
        #    field=models.EmailField(
        #        db_comment="이메일", max_length=50, unique=True, verbose_name="email"
        #    ),
        #),
    ]
